django_parent_child/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # add our app urls file
    url(r'^rel/', include('parent_child_app.urls')),
]

parent_child_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'pc'
urlpatterns = [
    url(r'^parents/$', views.parents, name='parents'),
    
    # (?P<>...) is a named parameter parent_id that can be picked up in the view 
    url(r'^children/(?P<parent_id>\d+)/$', views.children, name='children'),
]

parent_child_app/models.py
from django.db import models

class Parent(models.Model):

    firstname = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    age = models.IntegerField()

    def __str__(self):
        return self.firstname

class Child(models.Model):

    class Meta:
        # fix pluralisation on admin site so it doesn't
        # say 'childs'
        verbose_name_plural = "children"

    firstname = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    age = models.IntegerField()

    parent = models.ForeignKey(Parent)

    def __str__(self):
        return self.firstname

parent_child_app/views.py
from django.shortcuts import render_to_response
from .models import Parent, Child

def parents(request):
    """
    Return the parents
    """
    parent_list = Parent.objects.order_by('firstname')

    return render_to_response('parent_child_app/parents.html',
                            {'parent_list': parent_list})


def children(request, parent_id):
    """
    Return the children of a parent
    """
    child_list = Child.objects.filter(parent=parent_id).order_by('firstname')
    parent = Parent.objects.get(id=parent_id)

    return render_to_response('parent_child_app/children.html',
                            {'child_list': child_list,
                             'parent': parent})

parent_child_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Parents and their children</title>
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

parent_child_app/templates/parent_child_app/children.html
{% extends "base.html" %}

{% block content %}

<h2>Children of {{parent.firstname}} {{parent.surname}}</h2>
{% if child_list %}
    {% for child in child_list %}
        <div>
            {{ child.firstname }} who is {{ child.age }}.
        </div>
    {% endfor %}
{% else %}
    <div>
        There are no children yet.
    </div>
{% endif %}
<a href="{% url 'pc:parents' %}">   
    Back to parents
</a>

{% endblock %}

parent_child_app/templates/parent_child_app/parents.html
{% extends "base.html" %}

{% block content %}

<h2>Parents</h2>
{% if parent_list %}
    {% for parent in parent_list %}
        <div>
            {{ parent.firstname }}
            <a href="{% url 'pc:children' parent.id %}">   
                Children
            </a>
        </div>
    {% endfor %}
{% else %}
    <div>
        There are no parents yet.
    </div>
{% endif %}

{% endblock %}